import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// Dependency-free pack step: esbuild bundling was removed because esbuild is
// not declared in devDependencies and could not be added offline
// (ERR_PNPM_NO_OFFLINE_META). The shim re-exports the tsc output directly —
// dist/bin.js already runs under plain `node` (ESM, type: module), so a
// bundle was a nicety, not a requirement.
const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "dist", "clawmessenger.bundle.js");

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  [
    "#!/usr/bin/env node",
    "// Generated by scripts/pack.mjs — thin shim over dist/bin.js.",
    "import('./bin.js');",
    "",
  ].join("\n"),
);
chmodSync(out, 0o755);
console.log("wrote dist/clawmessenger.bundle.js — run with: node dist/clawmessenger.bundle.js <cmd>");
